#RabbitMQ Server configuration
spring:
  rabbitmq:
    host: javaschoolrmqrv2dutokzu7as-vm0.southcentralus.cloudapp.azure.com
    port: 5672
    username: user
    password: JavaSchool.1234

#Queue Configuration
queue:
  topic:
    name: db-exchange
  routing:
    key: "#"
  name: db-queue
#queue.topic.name=tut.rpc
#queue.routing.key=rpc