#RabbitMQ Server configuration
spring:
  rabbitmq:
    host: javaschoolrmqrv2dutokzu7as-vm0.southcentralus.cloudapp.azure.com
    port: 5672
    username: user
    password: JavaSchool.1234
    template:
      default-receive-queue: db-queue
      exchange: db-exchange
      routing-key: "#"

ui-url-request:
  package-types: packageType